### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by paramirez** [kkthemes/mmcss#1]
Hi , I'm interested as your project, i like to collaborate on a branch, is It Possible?

**Comment by kanishkkunal** [comment]
Hi @killcrops , Thank you for your request. This project is currently in pre-release state and I am not actually looking for additional collaborators for the project. However, I would love to hear your suggestions and you are welcome to send pull requests in case you find and fix any issues like browser support bugs.

Kindly open issues only for real issues in the project. You may contact me via Twitter or use [contact form](https://kanishkkunal.in/contact-me/) on my website for such personal requests in future. Thanks!
